const messages: Array<{
    top: number;
    left?: number;
    right?: number;
    image: string;
    profileName: string;
    message: string;
  }> = [
    { top: 150, left: 90, image: "https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&w=600", profileName: "Claus Maverick", message: "Hello World! I'm loving this awesome app!" },
    { top: 400, left: 170, image: "https://example.com/profile2.jpg", profileName: "André Mendes", message: "Amazing platform! Best way to stay connected." },
    { top: 150, right: 150, image: "https://example.com/profile3.jpg", profileName: "Jhon Jovi", message: "Communication has never been this smooth!" },
    { top: 500, right: 180, image: "https://example.com/profile4.jpg", profileName: "Albert Messon", message: "Hands down the best messaging app out there!" },
    { top: 200, left: 120, image: "https://example.com/profile5.jpg", profileName: "Sara Lima", message: "This app makes my day so much easier!" },
    { top: 300, right: 200, image: "https://example.com/profile6.jpg", profileName: "Mike Torres", message: "Super fast and reliable platform!" },
    { top: 250, left: 80, image: "https://example.com/profile7.jpg", profileName: "Julia Hart", message: "I can’t imagine my life without this app!" },
    { top: 450, right: 130, image: "https://example.com/profile8.jpg", profileName: "Lucas Brown", message: "Messaging perfection achieved!" },
    { top: 100, left: 200, image: "https://example.com/profile9.jpg", profileName: "Emma Stone", message: "Such a cool way to connect with people!" },
    { top: 350, right: 90, image: "https://example.com/profile10.jpg", profileName: "Pedro Silva", message: "This app is a game changer for sure!" },
    { top: 180, left: 150, image: "https://example.com/profile11.jpg", profileName: "Anna Lee", message: "Love how simple and effective this is!" },
    { top: 420, right: 160, image: "https://example.com/profile12.jpg", profileName: "Tom Harris", message: "The ultimate messaging experience!" },
    { top: 130, left: 110, image: "https://example.com/profile13.jpg", profileName: "Clara Jones", message: "Wow, this app is absolutely fantastic!" },
    { top: 470, right: 140, image: "https://example.com/profile14.jpg", profileName: "David Kim", message: "Super intuitive and fun to use!" },
    { top: 220, left: 100, image: "https://example.com/profile15.jpg", profileName: "Sophie Clark", message: "Messaging made easy and enjoyable!" },
    { top: 380, right: 120, image: "https://example.com/profile16.jpg", profileName: "Ryan Patel", message: "This platform is pure gold!" },
    { top: 160, left: 130, image: "https://example.com/profile17.jpg", profileName: "Lena Ortiz", message: "Best app for staying in touch!" },
    { top: 490, right: 170, image: "https://example.com/profile18.jpg", profileName: "James Carter", message: "Incredible design and functionality!" },
    { top: 140, left: 140, image: "https://example.com/profile19.jpg", profileName: "Mia Davis", message: "I’m obsessed with this app!" },
    { top: 410, right: 110, image: "https://example.com/profile20.jpg", profileName: "Noah Evans", message: "Top-notch communication tool!" },
    { top: 270, left: 160, image: "https://example.com/profile21.jpg", profileName: "Isabella Cruz", message: "So glad I found this platform!" },
    { top: 330, right: 190, image: "https://example.com/profile22.jpg", profileName: "Ethan Moore", message: "Fast, sleek, and awesome!" },
    { top: 190, left: 90, image: "https://example.com/profile23.jpg", profileName: "Olivia White", message: "This app is a total lifesaver!" },
    { top: 460, right: 150, image: "https://example.com/profile24.jpg", profileName: "Liam Hayes", message: "Perfect for all my messaging needs!" },
    { top: 120, left: 180, image: "https://example.com/profile25.jpg", profileName: "Ava King", message: "Highly recommend this to everyone!" },
    { top: 390, right: 100, image: "https://example.com/profile26.jpg", profileName: "Mason Reed", message: "This is the future of messaging!" },
    { top: 230, left: 110, image: "https://example.com/profile27.jpg", profileName: "Zoe Parker", message: "So user-friendly and cool!" },
    { top: 480, right: 130, image: "https://example.com/profile28.jpg", profileName: "Henry Ford", message: "A must-have app for everyone!" },
    { top: 170, left: 140, image: "https://example.com/profile29.jpg", profileName: "Lily Gray", message: "This app keeps me connected 24/7!" },
    { top: 430, right: 160, image: "https://example.com/profile30.jpg", profileName: "Jack Turner", message: "Brilliant platform, love it!" },
    { top: 200, left: 150, image: "https://example.com/profile31.jpg", profileName: "Ella Brooks", message: "Such an amazing messaging tool!" },
    { top: 360, right: 120, image: "https://example.com/profile32.jpg", profileName: "Owen Scott", message: "Really impressive app design!" },
    { top: 140, left: 100, image: "https://example.com/profile33.jpg", profileName: "Grace Hill", message: "I’m hooked on this platform!" },
    { top: 450, right: 170, image: "https://example.com/profile34.jpg", profileName: "Caleb Ward", message: "Messaging has never been better!" },
    { top: 180, left: 130, image: "https://example.com/profile35.jpg", profileName: "Nora Bell", message: "Fantastic app, super reliable!" },
    { top: 400, right: 140, image: "https://example.com/profile36.jpg", profileName: "Logan Price", message: "This app is my new favorite!" },
    { top: 220, left: 160, image: "https://example.com/profile37.jpg", profileName: "Chloe Adams", message: "So easy to use and fun!" },
    { top: 370, right: 110, image: "https://example.com/profile38.jpg", profileName: "Dylan Ross", message: "Top-tier messaging experience!" },
    { top: 160, left: 120, image: "https://example.com/profile39.jpg", profileName: "Hannah Cole", message: "Love this app so much!" },
    { top: 490, right: 180, image: "https://example.com/profile40.jpg", profileName: "Eli Parker", message: "Incredibly efficient platform!" },
    { top: 130, left: 140, image: "https://example.com/profile41.jpg", profileName: "Violet Lane", message: "This app is pure brilliance!" },
    { top: 420, right: 150, image: "https://example.com/profile42.jpg", profileName: "Isaac Fox", message: "Best way to stay in touch!" },
    { top: 190, left: 110, image: "https://example.com/profile43.jpg", profileName: "Ruby Diaz", message: "Can’t get enough of this app!" },
    { top: 460, right: 130, image: "https://example.com/profile44.jpg", profileName: "Samuel Lee", message: "Super slick and modern!" },
    { top: 150, left: 180, image: "https://example.com/profile45.jpg", profileName: "Lila Hayes", message: "This platform rocks!" },
    { top: 380, right: 100, image: "https://example.com/profile46.jpg", profileName: "Gabriel Cox", message: "Messaging made simple!" },
    { top: 210, left: 130, image: "https://example.com/profile47.jpg", profileName: "Aria Kim", message: "I’m loving every second of this!" },
    { top: 470, right: 160, image: "https://example.com/profile48.jpg", profileName: "Wyatt Bell", message: "This app is a total win!" },
    { top: 170, left: 150, image: "https://example.com/profile49.jpg", profileName: "Stella Ray", message: "Such a great experience!" },
    { top: 430, right: 120, image: "https://example.com/profile50.jpg", profileName: "Carter Dean", message: "Perfect app for communication!" },
    { top: 200, left: 140, image: "https://example.com/profile51.jpg", profileName: "Luna Hart", message: "This app is out of this world!" },
    { top: 350, right: 130, image: "https://example.com/profile52.jpg", profileName: "Miles Green", message: "Super cool platform!" },
    { top: 300, right: 150, image: "https://example.com/profile100.jpg", profileName: "Zara Quinn", message: "The best app I’ve ever used!" },
  ];

  export default messages;